import sqlite3
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "educacao_ia.db")

PLANOS_SEEDS = [
    # ========================== NÍVEL INICIANTE (A1 - A2) ==========================
    {
        "aula_numero": 1,
        "tema": "Se présenter",
        "nivel": "A1",
        "duracao": "50 min",
        "objetivos": "Aprender a se apresentar, dizer nome, nacionalidade, profissão e cumprimentar em francês.",
        "habilidades": "PO, PE, GR",
        "conteudos": "Pronoms sujets (je, tu, il/elle), verbe être au présent, vocabulário de apresentações e saudações.",
        "metodologia": "Abordagem comunicativa e método direto com repetição dialogada.",
        "recursos": "Slides ilustrados, cartões de identificação fictícios (Flashcards), áudio de diálogos curtos.",
        "etapa_aquecimento": "5-10 min: Professor cumprimenta os alunos em francês ('Bonjour!', 'Comment ça va?') e apresenta um crachá de identificação para ativar a curiosidade.",
        "etapa_apresentacao": "15 min: Introdução dos pronomes pessoais e do verbo 'être' (je suis, tu es, il/elle est). Modelagem de frases com profissões e nacionalidades.",
        "etapa_pratica": "15 min: Exercícios guiados de preenchimento de lacunas em duplas. Prática de pronúncia das terminações mudas e das ligações sonoras.",
        "etapa_producao": "10 min: Role-play: cada aluno recebe uma identidade francesa fictícia e circula pela sala se apresentando para 3 colegas.",
        "etapa_fechamento": "5 min: Síntese no quadro das formas do verbo être e recapitulação dos cumprimentos essenciais.",
        "avaliacao_formativa": "Exercício escrito: preencher ficha pessoal de identificação (fiche d'inscription).",
        "avaliacao_somativa": "Questão prática na Prova A1: conjugação de être e redação de apresentação de 4 linhas.",
        "dever_casa": "Escrever um parágrafo de 5 linhas apresentando a si mesmo e um amigo imaginário.",
        "reforco": "Exercícios adicionais no Assistente Fran sobre pronomes sujeitos e gravação de áudio de apresentação oral."
    },
    {
        "aula_numero": 2,
        "tema": "Ma famille",
        "nivel": "A1",
        "duracao": "50 min",
        "objetivos": "Descrever a árvore genealógica, falar dos membros da família e expressar posse.",
        "habilidades": "CO, CE, PO",
        "conteudos": "Vocabulário de parentesco, adjetivos possessivos (mon, ma, mes / ton, ta, tes), verbo avoir.",
        "metodologia": "Abordagem comunicativa baseada em árvores genealógicas e tarefas de escuta.",
        "recursos": "Árvore genealógica de personagens conhecidos, faixa de áudio de apresentação familiar, fichas.",
        "etapa_aquecimento": "5-10 min: Projeção de fotos de famílias famosas. Perguntas rápidas: 'Qui est-ce? C'est le père? C'est la mère?'.",
        "etapa_apresentacao": "15 min: Apresentação do vocabulário familiar e das regras de adjetivos possessivos (mon/ma/mes). Conjugação do verbo 'avoir'.",
        "etapa_pratica": "15 min: Escuta de um áudio descritivo familiar com marcação em questionário de múltipla escolha. Exercício em duplas com árvore genealógica muda.",
        "etapa_producao": "10 min: Mini-apresentação oral: o aluno desenha rapidamente 3 membros de sua família e os apresenta ao parceiro.",
        "etapa_fechamento": "5 min: Correção coletiva de dúvidas recorrentes de possessivos femininos iniciados por vogal (ex: mon amie).",
        "avaliacao_formativa": "Ditado de frases com termos familiares + diálogo em duplas sobre parentesco.",
        "avaliacao_somativa": "Compreensão oral na Prova A1 identificando relações de parentesco.",
        "dever_casa": "Desenhar a própria árvore genealógica com legendas completas em francês usando possessivos.",
        "reforco": "Treino interativo de vocabulário e ditado de frases com 'avoir' e 'famille' no Assistente Fran."
    },
    {
        "aula_numero": 3,
        "tema": "Au restaurant",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Fazer pedidos em cafés e restaurantes, perguntar preços e expressar polidez em francês.",
        "habilidades": "PO, IO, CO",
        "conteudos": "Artigos partitivos (du, de la, des), vocabulário alimentar, expressões de cortesia ('Je voudrais', 'S'il vous plaît').",
        "metodologia": "Abordagem ação-orientada através de simulação de papéis (Role-play realista).",
        "recursos": "Cardápios reais de bistrôs parisienses em PDF/impressos, moedas cenográficas fictícias, áudio de pedidos.",
        "etapa_aquecimento": "5-10 min: Apresentação de imagens de pratos típicos franceses (croissant, quiche, café crème). Levantamento do léxico já conhecido.",
        "etapa_apresentacao": "15 min: Explicação do uso dos partitivos e comparação com artigos definidos/indefinidos. Fórmulas de polidez essenciais.",
        "etapa_pratica": "15 min: Leitura compreensiva do cardápio em duplas. Associação de ingredientes e seleção de itens para compor um menu (entrée, plat, dessert).",
        "etapa_producao": "15 min: Role-play completo: um aluno atua como garçom (serveur) e o outro como cliente, negociando o pedido e pedindo a conta ('L'addition, s'il vous plaît').",
        "etapa_fechamento": "5 min: Destaque de erros comuns de partitivos (ex: pas de vs. du) e dicas de entonação interrogativa.",
        "avaliacao_formativa": "Role-play em duplas com rubrica: precisão no uso dos partitivos, fluência do pedido e fórmulas de cortesia.",
        "avaliacao_somativa": "Prova A2: Ditado de ingredientes e elaboração escrita de um diálogo em restaurante.",
        "dever_casa": "Escrever um diálogo completo de 10 linhas em um restaurante pedindo prato principal e sobremesa.",
        "reforco": "Jogo de cartas com vocabulário de alimentos e missão de reforço de artigos partitivos no Fran."
    },
    {
        "aula_numero": 4,
        "tema": "Ma journée",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Relatar a rotina diária, cronologia das atividades e expressar as horas.",
        "habilidades": "CE, GR, PE",
        "conteudos": "Verbos pronominais no presente (se réveiller, se lever, se coucher), verbos regulares do 1º grupo (-er), as horas.",
        "metodologia": "Sequência comunicativa com foco em linha do tempo cronológica.",
        "recursos": "Relógio pedagógico ilustrativo, tirinha em quadrinhos de uma rotina típica francesa.",
        "etapa_aquecimento": "5-10 min: Professor mostra horários no relógio e pergunta: 'Quelle heure est-il?'. Revisão relâmpago de números e horas.",
        "etapa_apresentacao": "15 min: Introdução da conjugação de verbos pronominais reflexivos (je me lève, tu te lèves) e conectores temporais (d'abord, ensuite, après).",
        "etapa_pratica": "15 min: Exercício de ordenação dos quadros de uma rotina desordenada com preenchimento da conjugação adequada.",
        "etapa_producao": "15 min: Redação individual de uma tabela diária: 'Une journée ordinaire', descrevendo desde o despertar até o repouso noturno.",
        "etapa_fechamento": "5 min: Leitura de duas produções em voz alta para refinamento da pronúncia do 'e' mudo nos verbos em -er.",
        "avaliacao_formativa": "Produção escrita: descrever sua rotina diária em pelo menos 6 ações sequenciais com horas.",
        "avaliacao_somativa": "Avaliação A2 de produção escrita com critérios de conectores e concordância de pronominais.",
        "dever_casa": "Gravar um áudio de 45 segundos no celular descrevendo seu dia favorito da semana.",
        "reforco": "Laboratório de conjugação de verbos pronominais e exercícios do radar no Assistente Fran."
    },
    {
        "aula_numero": 5,
        "tema": "En ville",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Localizar-se no espaço urbano, pedir e fornecer itinerários e direções em francês.",
        "habilidades": "CO, PO, IO",
        "conteudos": "Preposições de lugar (à côté de, en face de, entre), estruturas de orientação (tournez à gauche, continuez tout droit, prenez la première rue), 'il y a'.",
        "metodologia": "Gamificação através de mapas interativos e orientação no espaço.",
        "recursos": "Mapa simplificado do metrô e bairros de Paris, áudio de pedido de informação na rua.",
        "etapa_aquecimento": "5-10 min: Projeção de monumentos parisienses (Tour Eiffel, Louvre). Perguntas de localização: 'Où est le Louvre?'.",
        "etapa_apresentacao": "15 min: Ensino do imperativo para direções ('Prenez...', 'Allez...', 'Tournez...') e preposições de lugar com contrações (du, de la).",
        "etapa_pratica": "15 min: Atividade 'Suivez le guide': os alunos escutam um áudio e traçam a rota no mapa impresso com lápis colorido.",
        "etapa_producao": "15 min: Em duplas, Aluno A escolhe um destino secreto no mapa e guia verbalmente o Aluno B até o local correto.",
        "etapa_fechamento": "5 min: Validação dos destinos encontrados e revisão do vocabulário de pontos de referência (feu, carrefour, pont).",
        "avaliacao_formativa": "Atividade com mapa: dar e seguir instruções com precisão de termos e direção.",
        "avaliacao_somativa": "Compreensão oral na prova com traçado de itinerário a partir de instruções faladas.",
        "dever_casa": "Escrever um e-mail explicando como chegar da estação de trem até a sua casa em francês.",
        "reforco": "Quiz no aplicativo sobre contrações prepositivas e vocabulário de mobilidade urbana."
    },
    {
        "aula_numero": 6,
        "tema": "Le passé",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Compreender e formular frases no passado composto para narrar acontecimentos recentes.",
        "habilidades": "GR, CE, PE",
        "conteudos": "Introdução ao Passé Composé: auxiliares avoir e être, particípios regulares (-é, -i, -u), regras de concordância com être.",
        "metodologia": "Abordagem indutiva com identificação guiada em texto autêntico.",
        "recursos": "Trecho de diário de viagem (Journal de bord), tabela de verbos da casa de être (Maison d'être).",
        "etapa_aquecimento": "5-10 min: Linha do tempo visual no quadro: Présent vs. Passé. Frase provocativa: 'Qu'est-ce que vous avez fait hier?'.",
        "etapa_apresentacao": "15 min: Apresentação da estrutura Auxiliar no Presente + Particípio Passado. A 'Maison d'être' (verbos de movimento e reflexivos).",
        "etapa_pratica": "15 min: Exercícios de transformação de frases do presente para o passado em duplas com verificação imediata.",
        "etapa_producao": "15 min: Pequeno relato individual: 'Mon week-end dernier' (redação de 5 frases sobre o fim de semana passado).",
        "etapa_fechamento": "5 min: Alerta pedagógico sobre a diferença crucial entre 'j'ai mangé' e 'je suis allé'.",
        "avaliacao_formativa": "Exercícios de transformação de frases + pequeno relato de ações no fim de semana.",
        "avaliacao_somativa": "Prova escrita A2: identificação do auxiliar correto e concordância do particípio passado.",
        "dever_casa": "Concluir a ficha de exercícios de fixação do Passé Composé com os 14 verbos de être.",
        "reforco": "Exercícios de fixação de Passé Composé no Assistente Fran com correção imediata da IA."
    },
    {
        "aula_numero": 7,
        "tema": "Projets d'avenir",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Falar sobre projetos futuros imediatos, planos de férias e intenções.",
        "habilidades": "PO, PE, GR",
        "conteudos": "Estrutura do Futur Proche (aller au présent + infinitif), marcadores temporais de futuro (demain, le mois prochain, ce soir).",
        "metodologia": "Abordagem comunicativa centrada no compartilhamento de planos pessoais.",
        "recursos": "Catálogos de agências de viagens, infográficos de destinos turísticos francófonos.",
        "etapa_aquecimento": "5-10 min: Brainstorming: 'Quels sont vos projets pour les vacances?'. Anotação de verbos de lazer no quadro.",
        "etapa_apresentacao": "15 min: Estruturação gramatical do Futur Proche: conjugação do verbo 'aller' no presente + verbo principal no infinitivo. Uso da negação (je ne vais pas...).",
        "etapa_pratica": "15 min: Jogo de associação de frases em tiras de papel: relacionar desejos a ações futuras planejadas.",
        "etapa_producao": "15 min: Apresentação oral rápida: cada aluno expõe em 1 minuto seus planos para as próximas férias.",
        "etapa_fechamento": "5 min: Revisão das formas afirmativas e negativas do Futur Proche e feedback de pronúncia.",
        "avaliacao_formativa": "Produção oral rápida: 'O que vou fazer no fim de semana?' com rubrica de adequação temporal.",
        "avaliacao_somativa": "Questões de redação curta de planos futuros na avaliação somativa da unidade.",
        "dever_casa": "Elaborar um folheto turístico fictício intitulado 'Mon prochain voyage' com 6 frases no Futur Proche.",
        "reforco": "Atividades de revisão no radar do aluno do Assistente Fran combinando presente, passado e futuro."
    },
    {
        "aula_numero": 8,
        "tema": "Revisão e avaliação formativa A1/A2",
        "nivel": "A2",
        "duracao": "50 min",
        "objetivos": "Consolidar os conteúdos essenciais do ciclo inicial e verificar o domínio das competências comunicativas.",
        "habilidades": "Todas (CO, CE, PO, PE, IO, GR)",
        "conteudos": "Apresentação, Família, Rotina, Cidade, Passado e Futuro em perspectiva integrada.",
        "metodologia": "Revisão ativa em estações de aprendizagem e simulação de teste global.",
        "recursos": "Fichas de exercícios integrados, simulado digital no Assistente Fran, áudios de síntese.",
        "etapa_aquecimento": "5-10 min: 'Quiz Relâmpago' com 5 perguntas gerais de vocabulário e tempos verbais para quebrar o gelo.",
        "etapa_apresentacao": "10 min: Mapa mental no quadro integrando as estruturas gramaticais e comunicativas vistas ao longo do ciclo.",
        "etapa_pratica": "15 min: Resolução em pares de um simulado temático com questões de conjugação, compreensão e vocabulário.",
        "etapa_producao": "15 min: Simulação de prova multimodal no sistema (leitura oral, ditado e produção escrita curta).",
        "etapa_fechamento": "5 min: Orientações docentes finais, esclarecimento de dúvidas e devolutiva sobre o progresso.",
        "avaliacao_formativa": "Desempenho no simulado em pares e identificação de pontos fracos para remediação.",
        "avaliacao_somativa": "Prova A1/A2 no Assistente Fran com notas e relatórios analíticos automáticos.",
        "dever_casa": "Revisar as recomendações do relatório individual gerado pelo sistema e praticar as missões indicadas.",
        "reforco": "Trilha de remediação personalizada no módulo do aluno baseada no histórico de erros."
    },

    # ========================== NÍVEL INTERMEDIÁRIO (B1 - B2) ==========================
    {
        "aula_numero": 1,
        "tema": "Raconter au passé (Passé Composé vs. Imparfait)",
        "nivel": "B1",
        "duracao": "50 min",
        "objetivos": "Distinguir e alternar com precisão o Passé Composé e o Imparfait na narração de histórias passadas.",
        "habilidades": "GR, CE, PE",
        "conteudos": "Valores semânticos do Imparfait (descrição, contexto, hábito) vs. Passé Composé (ação pontual, mudança, quebra). Marcadores temporais.",
        "metodologia": "Análise textual contrastiva guiada seguida de produção criativa.",
        "recursos": "Conto policial curto ('Un fait divers'), tabela de contraste aspectual, cartões de conectores temporais.",
        "etapa_aquecimento": "5-10 min: Leitura da abertura de uma história: 'Il faisait nuit, la pluie tombait... tout à coup, le téléphone a sonné!'. Pergunta: qual verbo descreve o cenário e qual traz a ação?",
        "etapa_apresentacao": "15 min: Sistematização teórica do aspecto verbal: Imparfait como pano de fundo (arrière-plan) e Passé Composé como primeiro plano narrativo (premier plan).",
        "etapa_pratica": "15 min: Exercício de preenchimento lacunar de um fait divers real, justificando a escolha de cada tempo verbal.",
        "etapa_producao": "15 min: Reescrita de um parágrafo narrativo: os alunos recebem uma sequência de fatos e devem transformá-la em uma narrativa viva.",
        "etapa_fechamento": "5 min: Regra de ouro da alternância e feedback sobre o erro comum de usar Passé Composé para hábitos passados.",
        "avaliacao_formativa": "Reescrita de texto alternando tempos verbais com justificativa gramatical.",
        "avaliacao_somativa": "Redação de um récit au passé (120-150 palavras) na prova B1.",
        "dever_casa": "Redigir uma narrativa sobre um evento inesperado ou uma lembrança marcante da infância.",
        "reforco": "Treinamento contrastivo PC x IMP no laboratório gramatical do Assistente Fran."
    },
    {
        "aula_numero": 2,
        "tema": "L'environnement et la transition écologique",
        "nivel": "B1",
        "duracao": "50 min",
        "objetivos": "Debater questões ambientais, defender um ponto de vista e propor soluções ecológicas.",
        "habilidades": "CO, PO, IO",
        "conteudos": "Vocabulário ambiental (réchauffement, biodiversité, énergies renouvelables), expressões de opinião (à mon avis, je pense que, selon moi).",
        "metodologia": "Debate estruturado baseado em papéis (Role-play de conferência climática).",
        "recursos": "Podcast jornalístico curto da RFI Savoirs sobre consumo sustentável, infográfico sobre pegada de carbono.",
        "etapa_aquecimento": "5-10 min: Exibição de um infográfico com o 'Dia da Sobrecarga da Terra'. Debate relâmpago: o que você faz pelo planeta?",
        "etapa_apresentacao": "15 min: Escuta ativa do podcast com questões de interpretação global e detalhada. Levantamento do repertório argumentativo de opinião.",
        "etapa_pratica": "15 min: Em trios, categorizar causas, consequências e soluções ambientais a partir do material de áudio.",
        "etapa_producao": "15 min: Debate simulado: 'Faut-il interdire les vols courts en avion?'. Grupos defendem posições favoráveis e contrárias.",
        "etapa_fechamento": "5 min: Conclusão do debate, destaque de argumentos fortes e correção de interferências do português.",
        "avaliacao_formativa": "Debate em sala avaliado por rubrica de interação oral e pertinência vocabular.",
        "avaliacao_somativa": "Questão discursiva na prova B1 expondo vantagens e desvantagens de medidas ecológicas.",
        "dever_casa": "Escrever um artigo de opinião curto (100 palavras) para um jornal escolar sobre reciclagem.",
        "reforco": "Estudo de caso no fórum do aplicativo sobre transição energética com comentários moderados pela IA."
    },
    {
        "aula_numero": 3,
        "tema": "Le monde du travail et l'entretien d'embauche",
        "nivel": "B1",
        "duracao": "50 min",
        "objetivos": "Apresentar competências profissionais, responder a perguntas de entrevista e expressar condições/desejos.",
        "habilidades": "PO, PE, GR",
        "conteudos": "Conditionnel Présent (fórmulas de polidez e hipótese: j'aimerais, je pourrais, je souhaiterais), vocabulário corporativo e competências (soft skills).",
        "metodologia": "Simulação profissional de entrevista de recrutamento em pares.",
        "recursos": "Anúncio de vaga de emprego autêntico da França, modelo de CV em formato Europass, guia de perguntas de entrevista.",
        "etapa_aquecimento": "5-10 min: Brainstorming: quais qualidades são mais valorizadas em um ambiente de trabalho francófono?",
        "etapa_apresentacao": "15 min: Formação e usos do Condicional Presente. Análise de fórmulas de apresentação profissional em e-mails e entrevistas.",
        "etapa_pratica": "15 min: Elaboração de respostas estratégicas para as 3 perguntas clássicas: 'Parlez-moi de vous', 'Vos points forts', 'Pourquoi ce poste?'.",
        "etapa_producao": "15 min: Simulação cruzada de entrevista: cada aluno atua como recrutador por 7 minutos e como candidato por 7 minutos.",
        "etapa_fechamento": "5 min: Dicas de postura e vocabulário formal francófono ('lettre de motivation', 'stage', 'télétravail').",
        "avaliacao_formativa": "Simulação: entrevista de emprego com avaliação formativa dos pares e do professor.",
        "avaliacao_somativa": "Redação formal de carta de apresentação profissional na avaliação somativa B1.",
        "dever_casa": "Redigir uma carta de motivação (lettre de motivation) de 120 palavras respondendo à vaga trabalhada.",
        "reforco": "Missão no Assistente Fran de conjugação de verbos no condicional e escrita de mensagens formais."
    },
    {
        "aula_numero": 4,
        "tema": "Les médias et l'information",
        "nivel": "B2",
        "duracao": "50 min",
        "objetivos": "Analisar notícias, identificar fake news e relatar declarações usando o discurso indireto no passado.",
        "habilidades": "CE, GR, CO",
        "conteudos": "Discours rapporté / indirect au passé (concordância de tempos: présent -> imparfait, passé composé -> plus-que-parfait, futur -> conditionnel).",
        "metodologia": "Leitura crítica da mídia e exercício prático de redação jornalística.",
        "recursos": "Manchetes de jornais franceses (Le Monde, Le Figaro), áudio de boletim informativo da rádio France Info.",
        "etapa_aquecimento": "5-10 min: Comparação de manchetes sensacionalistas vs. jornalismo investigativo: como identificar fontes confiáveis?",
        "etapa_apresentacao": "15 min: Regras formais da transposição do discurso direto para o discurso indireto no passado com verbos introdutores (déclarer, affirmer, expliquer).",
        "etapa_pratica": "15 min: Transformação de entrevistas gravadas em citações jornalísticas em discurso indireto.",
        "etapa_producao": "15 min: Redação de uma síntese de notícia a partir de duas declarações conflitantes de testemunhas.",
        "etapa_fechamento": "5 min: Revisão das alterações de pronomes e marcadores temporais (aujourd'hui -> ce jour-là, demain -> le lendemain).",
        "avaliacao_formativa": "Síntese escrita de artigo de jornal com aplicação correta do discurso indireto.",
        "avaliacao_somativa": "Prova B2: questão de transposição de discurso e análise crítica de texto jornalístico.",
        "dever_casa": "Escolher uma notícia em francês e escrever um relato de 8 linhas transpondo as falas dos entrevistados.",
        "reforco": "Exercícios específicos de discurso indireto no Passé no módulo de reforço individual da Fran."
    },
    {
        "aula_numero": 5,
        "tema": "Voyager et faire une réclamation",
        "nivel": "B2",
        "duracao": "50 min",
        "objetivos": "Expressar sentimentos, desejos, hipóteses e redigir uma reclamação formal fundamentada.",
        "habilidades": "PO, PE, GR",
        "conteudos": "Introdução e consolidação do Subjonctif Présent (il faut que, je veux que, il est dommage que, bien que), conectores de oposição.",
        "metodologia": "Resolução de problemas do mundo real (imprevisto em viagem).",
        "recursos": "Cenário de viagem frustrada (voo cancelado, hotel sem água quente), modelo de carta de reclamação da SNCF/companhia aérea.",
        "etapa_aquecimento": "5-10 min: Compartilhamento de experiências de perrengues de viagem: 'Quelle a été votre pire expérience de voyage?'.",
        "etapa_apresentacao": "15 min: O modo Subjuntivo: valor de subjetividade, incerteza e sentimento. Verbos com radical irregular no subjuntivo.",
        "etapa_pratica": "15 min: Associação de matrizes de sentimento ao subjuntivo vs. indicativo (penser que + indicatif vs. ne pas penser que / il faut que + subjonctif).",
        "etapa_producao": "15 min: Redação individual de uma carta de reclamação formal exigindo reembolso e compensação usando estruturas no subjuntivo.",
        "etapa_fechamento": "5 min: Verificação das terminações universais do subjuntivo (-e, -es, -e, -ions, -iez, -ent).",
        "avaliacao_formativa": "Produção escrita: carta de reclamação avaliada por critérios DELF B2 (registro, argumentação e subjuntivo).",
        "avaliacao_somativa": "Avaliação formal com exercício gramatical de subjuntivo e redação argumentativa de protesto.",
        "dever_casa": "Finalizar a carta formal de reclamação para o diretor do hotel com argumentos adicionais.",
        "reforco": "Treinamento intensivo de subjuntivo x indicativo no Assistente Fran com exemplos práticos."
    },
    {
        "aula_numero": 6,
        "tema": "La santé, le bien-être et le système médical",
        "nivel": "B2",
        "duracao": "50 min",
        "objetivos": "Descrever sintomas, compreender prescrições médicas e utilizar os pronomes adverbiais com precisão.",
        "habilidades": "CO, CE, IO",
        "conteudos": "Pronomes 'Y' e 'EN' (substituição de lugares e complementos introduzidos por de/à), vocabulário do corpo humano e patologias.",
        "metodologia": "Role-play simulado em consultório médico com foco comunicativo.",
        "recursos": "Bula de medicamento em francês, formulário da Sécurité Sociale (Carte Vitale), ficha clínica simulada.",
        "etapa_aquecimento": "5-10 min: Mímica de sintomas (dor de cabeça, febre, tosse). Os alunos adivinham e nomeiam o problema em francês.",
        "etapa_apresentacao": "15 min: O papel sintático dos pronomes 'Y' (lieu / à + chose) e 'EN' (quantité / de + chose). Posição na frase afirmativa e negativa.",
        "etapa_pratica": "15 min: Exercício de substituição pronominal em diálogos de consulta médica (ex: 'Vous allez chez le médecin? Oui, j'y vais').",
        "etapa_producao": "15 min: Role-play médico/paciente: o paciente descreve seus hábitos e o médico dá orientações usando 'y' e 'en' ('Pensez-y', 'Prenez-en deux par jour').",
        "etapa_fechamento": "5 min: Síntese comparativa entre pronomes complementos diretos/indiretos (COD/COI) e os pronomes Y/EN.",
        "avaliacao_formativa": "Role-play: consulta médica com verificação do uso natural dos pronomes Y e EN.",
        "avaliacao_somativa": "Questões de substituição pronominal e interpretação de texto médico na prova B2.",
        "dever_casa": "Escrever um diálogo de aconselhamento de saúde entre dois amigos contendo pelo menos 3 pronomes Y e 3 pronomes EN.",
        "reforco": "Prática guiada de pronomes no assistente com foco em posições verbais e tempos compostos."
    },
    {
        "aula_numero": 7,
        "tema": "Faits de société et débats d'actualité",
        "nivel": "B2",
        "duracao": "50 min",
        "objetivos": "Construir uma argumentação estruturada, refutar ideias opostas e utilizar conectores lógicos de nuance.",
        "habilidades": "PO, PE, IO",
        "conteudos": "Conectores lógicos de causa, consequência, oposição e concessão (bien que, néanmoins, par conséquent, en revanche, puisque).",
        "metodologia": "Oficina de argumentação socrática e síntese de ideias.",
        "recursos": "Dossiê temático sobre impacto do teletrabalho na sociedade com artigos curtos prós e contras.",
        "etapa_aquecimento": "5-10 min: Pergunta-provocação: 'Le télétravail isole-t-il les gens ou libère-t-il du temps?'. Posições rápidas dos alunos.",
        "etapa_apresentacao": "15 min: Estrutura do parágrafo argumentativo francófono (Idée, Argument, Exemple). Conectores de concessão e contraste.",
        "etapa_pratica": "15 min: Análise de um texto argumentativo: sublinhar a ideia principal e identificar a transição de conectores lógicos.",
        "etapa_producao": "15 min: Elaboração e apresentação de uma dissertação curta oral de 2 minutos defendendo uma tese com 2 argumentos e 1 contra-argumento.",
        "etapa_fechamento": "5 min: Feedback do professor sobre o encadeamento das ideias e riqueza de conectores utilizados.",
        "avaliacao_formativa": "Dissertação curta oral gravada ou apresentada com rubrica de conectores e coesão textual.",
        "avaliacao_somativa": "Prova B2 com redação argumentativa formal de 250 palavras.",
        "dever_casa": "Escrever a introdução e o primeiro parágrafo de um ensaio dissertativo sobre o tema da aula.",
        "reforco": "Fórum de debate socrático no Assistente Fran com mediação de IA pedagógica."
    },
    {
        "aula_numero": 8,
        "tema": "Revisão integrada e avaliação somativa B1/B2",
        "nivel": "B2",
        "duracao": "50 min",
        "objetivos": "Avaliar o domínio consolidado de tempos narrativos, discurso indireto, subjuntivo e argumentação.",
        "habilidades": "Todas (CO, CE, PO, PE, IO, GR)",
        "conteudos": "Síntese dos tópicos de B1 e B2 em formato preparatório para certificação DELF.",
        "metodologia": "Simulação de exame em formato padrão DELF B1/B2.",
        "recursos": "Prova modelo DELF, áudio de compreensão oral longa, critérios de avaliação do CEFR.",
        "etapa_aquecimento": "5-10 min: Estratégias de realização de provas: gestão do tempo e leitura atenta dos enunciados.",
        "etapa_apresentacao": "10 min: Revisão relâmpago dos 4 pilares avaliativos (compreensão oral, leitura, produção escrita e gramática em contexto).",
        "etapa_pratica": "15 min: Resolução da seção de compreensão oral e escrita do simulado.",
        "etapa_producao": "15 min: Redação do ensaio argumentativo / submissão no sistema para avaliação automatizada.",
        "etapa_fechamento": "5 min: Balanço do simulado, expectativas de notas e orientações para o nível avançado C1.",
        "avaliacao_formativa": "Autoavaliação guiada com gabarito comentado.",
        "avaliacao_somativa": "Prova B1/B2 completa (com redação dissertativa + audição longa) gerada no Assistente Fran.",
        "dever_casa": "Analisar os erros cometidos na prova e elaborar plano de estudo individual.",
        "reforco": "Revisão dirigida nas fraquezas apontadas no painel docente e radar de reforço."
    },

    # ========================== NÍVEL AVANÇADO (C1 - C2) ==========================
    {
        "aula_numero": 1,
        "tema": "L'art de convaincre et la rhétorique avancée",
        "nivel": "C1",
        "duracao": "50 min",
        "objetivos": "Dominar figuras de retórica, argumentação complexa e subjuntivo avançado para persuasão formal.",
        "habilidades": "PO, PE, IO",
        "conteudos": "Subjuntivo pretérito, figuras de estilo (métaphore, litote, anaphore), modalizadores de certeza e dúvida nuanceada.",
        "metodologia": "Análise de discursos clássicos francófonos e oratória deliberativa.",
        "recursos": "Trecho de discurso histórico (ex: Robert Badinter sobre a abolição da pena de morte, Simone Veil), roteiro de análise estilística.",
        "etapa_aquecimento": "5-10 min: Escuta de 1 minuto de um discurso memorável: como o orador capta a atenção logo nas primeiras palavras?",
        "etapa_apresentacao": "15 min: Estudo dos recursos retóricos de persuasão e do emprego do subjuntivo passado para expressar anterioridade com nuance.",
        "etapa_pratica": "15 min: Reescrever um texto neutro adicionando ênfase, anáforas e modalizadores estilísticos refinados.",
        "etapa_producao": "15 min: Exposé oral estruturado de 3 minutos sobre uma causa humanitária ou social, aplicando a retórica ensinada.",
        "etapa_fechamento": "5 min: Análise da cadência, postura de voz e escolha lexical dos oradores.",
        "avaliacao_formativa": "Exposé estruturado avaliado por critérios de impacto retórico e precisão sintática.",
        "avaliacao_somativa": "Apresentação oral formal e ensaio retórico na avaliação C1.",
        "dever_casa": "Escrever um manifesto de 15 linhas apelando à consciência coletiva sobre um desafio contemporâneo.",
        "reforco": "Desafios C1 com geração de questões de estilo e vocabulário erudito no Assistente Fran."
    },
    {
        "aula_numero": 2,
        "tema": "Littérature francophone et critique littéraire",
        "nivel": "C1",
        "duracao": "50 min",
        "objetivos": "Analisar textos literários clássicos e contemporâneos, interpretar metáforas e redigir comentários críticos.",
        "habilidades": "CE, PO",
        "conteudos": "Vocabulário de crítica literária, tempos literários (passé simple na leitura, subjonctif imparfait para reconhecimento), análise estilística.",
        "metodologia": "Leitura analítica aprofundada (explication de texte à la française).",
        "recursos": "Excerto de obra literária francófona (Camus, Proust, Maryse Condé ou Tahar Ben Jelloun).",
        "etapa_aquecimento": "5-10 min: Leitura expressiva de um poema ou microconto em voz alta. Sensações provocadas pela sonoridade e ritmo.",
        "etapa_apresentacao": "15 min: O método francês da 'Explication de texte': estrutura em eixos de leitura, tese do autor e recursos estilísticos.",
        "etapa_pratica": "15 min: Trabalho em duplas: identificar os campos lexicais dominantes e as figuras de linguagem no trecho fornecido.",
        "etapa_producao": "15 min: Debate literário mediado: confronto de interpretações sobre o desfecho da narrativa e a voz do narrador.",
        "etapa_fechamento": "5 min: Síntese das conclusões estilísticas e recomendações de leitura de autores francófonos contemporâneos.",
        "avaliacao_formativa": "Análise literária oral e escrita de um fragmento com fundamentação de hipóteses.",
        "avaliacao_somativa": "Comentário de texto na prova C1 avaliando rigor analítico e vocabulário crítico.",
        "dever_casa": "Redigir uma resenha crítica de 200 palavras sobre o trecho literário analisado.",
        "reforco": "Trilha de literatura e vocabulário culto no assistente com contextualização sociocultural."
    },
    {
        "aula_numero": 3,
        "tema": "Débats de société et synthèse de documents",
        "nivel": "C1",
        "duracao": "50 min",
        "objetivos": "Sintetizar múltiplos documentos divergentes em um texto coeso e neutro sem emitir opinião pessoal inicial.",
        "habilidades": "CO, CE, PO, PE",
        "conteudos": "Técnica da 'Synthèse de documents' (formato DALF C1), paráfrase avançada, neutralidade jornalística e plano temático.",
        "metodologia": "Oficina metodológica de preparação direta para o exame DALF C1.",
        "recursos": "Dossiê com 3 documentos (artigo sociológico, gráfico estatístico e artigo de imprensa) sobre a inteligência artificial no trabalho.",
        "etapa_aquecimento": "5-10 min: Apresentação da temática: 'L'intelligence artificielle va-t-elle détruire ou réinventer le travail?'. Levantamento de ideias.",
        "etapa_apresentacao": "15 min: As regras estritas da synthèse DALF C1: proibição do 'eu', fidelidade aos textos originais, reformulação obrigatória.",
        "etapa_pratica": "15 min: Elaboração do quadro sinóptico comparativo: cruzar os 3 documentos identificando convergências e divergências.",
        "etapa_producao": "15 min: Redação coletiva ou individual da introdução com problemática e do primeiro eixo temático da síntese.",
        "etapa_fechamento": "5 min: Check-list de conformidade: neutralidade, número de palavras, presença de todos os documentos e ausência de plágio.",
        "avaliacao_formativa": "Exercício de 'Synthèse de documents' com rubrica oficial do exame DALF.",
        "avaliacao_somativa": "Prova somativa C1 com prova de síntese de documentos e ensaio argumentativo subsequente.",
        "dever_casa": "Concluir a redação da síntese completa respeitando o limite de 220 palavras (+/- 10%).",
        "reforco": "Avaliação de sínteses com correção gramatical e sugestão de sinônimos avançados pela IA."
    },
    {
        "aula_numero": 4,
        "tema": "Les registres de langue et la pragmatique linguistique",
        "nivel": "C1",
        "duracao": "50 min",
        "objetivos": "Transitar com maestria entre os registros soutenu (culto/formal), courant (padrão) e familier/argotique (coloquial).",
        "habilidades": "CE, PO, GR",
        "conteudos": "Registros de língua, ardor da linguagem jovem e verlan, fórmulas protocolares da alta administração e diplomacia francesa.",
        "metodologia": "Linguística aplicada e sociolinguística contrastiva com dramatização.",
        "recursos": "Tabela de equivalências de termos em 3 colunas (soutenu/courant/familier), trechos de filmes franceses e cartas oficiais.",
        "etapa_aquecimento": "5-10 min: Leitura de duas mensagens com o mesmo significado: uma em linguagem de rua/verlan e outra protocolar. Análise de humor e contexto.",
        "etapa_apresentacao": "15 min: Fenômenos da linguagem familiar (elipses, supressão do 'ne', gírias) vs. elegância do soutenu (inversão sujeito-verbo, vocabulário nobre).",
        "etapa_pratica": "15 min: Jogo de transposição: transformar um e-mail informal de WhatsApp em uma correspondência oficial para um reitor universitário.",
        "etapa_producao": "15 min: Dramatização em duplas: encenar uma mesma situação (ex: pedir desculpas por um atraso) nos 3 registros diferentes.",
        "etapa_fechamento": "5 min: Reflexão sobre adequação sociolinguística: 'Quand et avec qui peut-on tutoyer ou utiliser l'argot?'.",
        "avaliacao_formativa": "Transformação de registros em textos e adequação pragmática oral.",
        "avaliacao_somativa": "Questões de transposição estilística na prova C1.",
        "dever_casa": "Reescrever um parágrafo coloquial em francês culto refinado digno de um discurso acadêmico.",
        "reforco": "Prática de vocabulário e registros de linguagem no Assistente Fran."
    },
    {
        "aula_numero": 5,
        "tema": "Le monde du numérique et l'éthique technológica",
        "nivel": "C2",
        "duracao": "50 min",
        "objetivos": "Discutir dilemas éticos complexos da era digital, biossegurança e soberania de dados com fluência quase nativa.",
        "habilidades": "CE, PE",
        "conteudos": "Léxico técnico e filosófico especializado, construções impessoais avançadas, nominalização e densidade sintática.",
        "metodologia": "Seminário filosófico de debate bioético e ensaio dissertativo aprofundado.",
        "recursos": "Artigo do jornal 'Philosophie Magazine' sobre transumanismo e IA, trecho de parecer da comissão de ética francesa.",
        "etapa_aquecimento": "5-10 min: Dilema moral projetado: 'Faut-il accorder des droits aux robots intelligents?'. Tomada de posição imediata.",
        "etapa_apresentacao": "15 min: Análise da estrutura argumentativa de textos filosóficos contemporâneos franceses. Técnicas de nominalização para sintetizar ideias.",
        "etapa_pratica": "15 min: Exercício de refinamento estilístico: transformar frases com verbos longos em sentenças nominais densas e elegantes.",
        "etapa_producao": "15 min: Redação do plano detalhado de um ensaio no padrão DALF C2: tese, antítese e síntese dialética.",
        "etapa_fechamento": "5 min: Apreciação da sofisticação sintática das propostas apresentadas pelos estudantes.",
        "avaliacao_formativa": "Elaboração de ensaio argumentativo denso nos moldes da prova do DALF C2.",
        "avaliacao_somativa": "Ensaio dissertativo-argumentativo formal de 350 palavras na avaliação C2.",
        "dever_casa": "Escrever a introdução e os dois primeiros parágrafos do ensaio argumentativo sobre bioética digital.",
        "reforco": "Treino no assistente Fran com correção de estilo e ampliação de vocabulário acadêmico."
    },
    {
        "aula_numero": 6,
        "tema": "Culture, identité et universalisme francophone",
        "nivel": "C2",
        "duracao": "50 min",
        "objetivos": "Analisar a pluriculturalidade no espaço francófono, identificar ironia, duplo sentido e provérbios com precisão cultural.",
        "habilidades": "CO, CE, PO",
        "conteudos": "Expressões idiomáticas avançadas, figuras de ironia, intertextualidade, debates sobre a laicidade e o modelo republicano francês.",
        "metodologia": "Análise cultural crítica de crônicas e cinema de autor.",
        "recursos": "Crônica de rádio cultural (France Culture), trecho de filme francês contemporâneo com diálogos sutis.",
        "etapa_aquecimento": "5-10 min: Interpretação de expressões idiomáticas coloridas ('Avoir le cafard', 'Poser un lapin', 'Mettre son grain de sel').",
        "etapa_apresentacao": "15 min: Os conceitos republicanos franceses (Laïcité, Universalisme) e as visões da francofonia no Magrebe, África subsariana e Quebec.",
        "etapa_pratica": "15 min: Análise de uma crônica satírica: sublinhar onde reside a ironia e os implícitos culturais (non-dits).",
        "etapa_producao": "15 min: Mesa-redonda: 'La diversité linguistique au sein de la francophonie: enrichissement ou menace?'.",
        "etapa_fechamento": "5 min: Destaque sobre como a proficiência C2 exige domínio não apenas da língua, mas dos códigos culturais partilhados.",
        "avaliacao_formativa": "Análise de filme/crônica com identificação de implícitos culturais e ironia.",
        "avaliacao_somativa": "Prova de compreensão oral longa e análise de conotações na avaliação somativa C2.",
        "dever_casa": "Escrever uma crônica de costumes de 150 palavras utilizando pelo menos duas expressões idiomáticas com ironia sutil.",
        "reforco": "Exploração do guia cultural e gramatical FLE integrado no Assistente Fran."
    },
    {
        "aula_numero": 7,
        "tema": "Médias, post-vérité et nuances de l'opinion",
        "nivel": "C2",
        "duracao": "50 min",
        "objetivos": "Detectar vieses ideológicos, manipular a nuance argumentativa com requinte e redigir artigo de opinião opinativo de alto impacto.",
        "habilidades": "CE, PE, IO",
        "conteudos": "Vocabulário editorial jornalístico sofisticado, orações concessivas de alto nível, modulação do tom opinativo.",
        "metodologia": "Comitê de redação jornalística e redação editorial rápida.",
        "recursos": "Editoriais de dois grandes periódicos franceses de linhas políticas opostas sobre o mesmo tema político.",
        "etapa_aquecimento": "5-10 min: Leitura apenas do título e subtítulo de dois editoriais. Pergunta: qual o posicionamento político de cada autor?",
        "etapa_apresentacao": "15 min: Como os adjetivos e advérbios modalizadores traem a neutralidade e moldam a opinião pública em francês.",
        "etapa_pratica": "15 min: Reescrever um parágrafo neutro transformando-o em um editorial incisivo favorável ou crítico à tese em discussão.",
        "etapa_producao": "15 min: Redação de um 'Billet d'humeur' ou coluna de opinião individual com argumentação incisiva.",
        "etapa_fechamento": "5 min: Leitura em voz alta de trechos selecionados com ênfase e entonação jornalística.",
        "avaliacao_formativa": "Redação de artigo de opinião avaliado segundo critérios do DALF C2.",
        "avaliacao_somativa": "Produção escrita na prova C2 exigindo defesa contundente de uma tese com refutação.",
        "dever_casa": "Polir o artigo de opinião e formatá-lo como um texto pronto para publicação em um blog acadêmico.",
        "reforco": "Simulação de ensaios com feedback formativo e avaliação de coerência no sistema Fran."
    },
    {
        "aula_numero": 8,
        "tema": "Bilan global et simulation DALF C1/C2",
        "nivel": "C2",
        "duracao": "50 min",
        "objetivos": "Validar a maestria linguística plena, capacidade de síntese e expressão autônoma de nível C1/C2.",
        "habilidades": "Todas (CO, CE, PO, PE, IO, GR)",
        "conteudos": "Síntese dos tópicos de nível avançado em formato equivalente ao Diploma Aprofundado de Língua Francesa (DALF).",
        "metodologia": "Simulação completa e devolutiva analítica baseada no Quadro Europeu Comum (QECR).",
        "recursos": "Dossiê completo de exame C1/C2 do Assistente Fran com áudios e textos autênticos.",
        "etapa_aquecimento": "5-10 min: Aquecimento mental: dicas de gestão de estresse e postura em exposições de alto nível.",
        "etapa_apresentacao": "10 min: Apresentação da grade de avaliação de proficiência C1/C2 (precisão fonética, amplitude lexical, correção sintática).",
        "etapa_pratica": "15 min: Resolução da parte de compreensão auditiva e análise de documento longo.",
        "etapa_producao": "15 min: Redação da proposta dissertativa final / gravação da defesa oral no módulo de áudio.",
        "etapa_fechamento": "5 min: Considerações finais, encerramento do ciclo e emissão do diagnóstico consolidado de proficiência.",
        "avaliacao_formativa": "Devolutiva detalhada com rubrica das competências avançadas.",
        "avaliacao_somativa": "Prova C1/C2 completa (ensaio dissertativo de alto padrão + audição complexa) registrada no sistema.",
        "dever_casa": "Revisar os pontos de melhoria destacados no relatório acadêmico individual.",
        "reforco": "Acesso contínuo ao Fórum Socrático e desafios diários de manutenção do nível avançado no Fran."
    }
]

def init_planos_aula(conn=None):
    """Cria a tabela planos_aula e insere os 24 planos pedagógicos se a tabela estiver vazia."""
    close_after = False
    if conn is None:
        conn = sqlite3.connect(DB_PATH)
        close_after = True

    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS planos_aula (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            aula_numero INTEGER DEFAULT 1,
            tema TEXT NOT NULL,
            nivel TEXT NOT NULL,
            duracao TEXT NOT NULL,
            objetivos TEXT NOT NULL,
            habilidades TEXT NOT NULL,
            conteudos TEXT NOT NULL,
            metodologia TEXT NOT NULL,
            recursos TEXT NOT NULL,
            etapa_aquecimento TEXT,
            etapa_apresentacao TEXT,
            etapa_pratica TEXT,
            etapa_producao TEXT,
            etapa_fechamento TEXT,
            avaliacao_formativa TEXT,
            avaliacao_somativa TEXT,
            dever_casa TEXT,
            reforco TEXT,
            turma_id INTEGER,
            criador_id INTEGER DEFAULT 1,
            data_criacao TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (turma_id) REFERENCES turmas(id) ON DELETE SET NULL,
            FOREIGN KEY (criador_id) REFERENCES professores(id) ON DELETE CASCADE
        );
    """)

    cursor.execute("SELECT COUNT(*) FROM planos_aula;")
    total = cursor.fetchone()[0]

    if total == 0:
        print(f"[*] Inserindo {len(PLANOS_SEEDS)} planos de aula de referência pedagógica FLE...")
        for p in PLANOS_SEEDS:
            cursor.execute("""
                INSERT INTO planos_aula (
                    aula_numero, tema, nivel, duracao, objetivos, habilidades,
                    conteudos, metodologia, recursos, etapa_aquecimento,
                    etapa_apresentacao, etapa_pratica, etapa_producao,
                    etapa_fechamento, avaliacao_formativa, avaliacao_somativa,
                    dever_casa, reforco, criador_id
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
            """, (
                p["aula_numero"], p["tema"], p["nivel"], p["duracao"], p["objetivos"], p["habilidades"],
                p["conteudos"], p["metodologia"], p["recursos"], p["etapa_aquecimento"],
                p["etapa_apresentacao"], p["etapa_pratica"], p["etapa_producao"],
                p["etapa_fechamento"], p["avaliacao_formativa"], p["avaliacao_somativa"],
                p["dever_casa"], p["reforco"]
            ))
        conn.commit()
        print(f"[+] Sucesso! {len(PLANOS_SEEDS)} planos de aula foram cadastrados no banco de dados.")
    else:
        print(f"[i] Tabela planos_aula já contém {total} planos cadastrados.")

    if close_after:
        conn.close()

if __name__ == "__main__":
    init_planos_aula()
